### ISSUE TITLE
Windows dll names without versioning

### ISSUE THREAD

**Issue by evetion** [JuliaGeo/PROJBuilder#4]
The Windows build only has a versioned dll, which is often not picked up by automatic build systems.

I had to run the following to fix this when building GDAL.
`ln -s $prefix/lib/libproj_6_1.dll.a $prefix/lib/libproj.dll.a`

Could we provide this automatically?

**Comment by visr** [comment]
As @evetion noted this is also used in [GDAL CI scripts](https://github.com/OSGeo/gdal/blob/6ad7dccaf6aa2dba826d160df552a982bd9a406a/gdal/ci/travis/osx/install.sh#L62).

Not sure if adding this step here is the right thing to do though. In that case it should have been part of the PROJ `make install` steps. Seems like something that should be changed in the GDAL build process. But until then adding the workaround to GDALBuilder seems fine to me as well.

**Comment by visr** [comment]
Closing due to archiving this repository.
